### PR TITLE
Update to CDN that the Mermaid docs use

### LINKED ISSUE #110: mermaid cdn change?
I am currently getting a CDN error on diagrams that worked previously. 

I noticed that [the mermaid.js docs](https://mermaid.js.org/intro/n00b-gettingStarted.html#requirements-for-the-mermaid-api) use a different cdn now than what this package loads:

docs:
```
  <script type="module">
    import mermaid from 'https://cdn.jsdelivr.net/npm/mermaid@10/dist/mermaid.esm.min.mjs';
    mermaid.initialize({ startOnLoad: true });
  </script>
```

from building a jupyterbook with this extension:
```
<script src="https://unpkg.com/mermaid/dist/mermaid.min.js"></script>
    <script>mermaid.initialize({startOnLoad:true});</script>
```

I have verified that manually editing the built html makes the images render.

### PR DESCRIPTION
**Pull request by brownsarahm**
closes #110

### CODE REVIEW

**Review by kiersten-stokes — APPROVED** [review]
FWIW as a non-maintainer, I've tested and working from me!

**Comment by spydon** [comment]
I guess this can be closed since it was fixed [here](https://github.com/mgaitan/sphinxcontrib-mermaid/commit/2eaff4220ade181ad9d8e6148f76498c0c0671f2) and released in 0.8.1

**Comment by brownsarahm** [comment]
No, that change did not fix the issue that I found, it change the version to handle that there was a breaking change in mermaid, but not the fact that [the mermaid.js docs](https://mermaid.js.org/intro/n00b-gettingStarted.html#requirements-for-the-mermaid-api)  advise using jsdelvier CDN not unpkg

**Comment by nils-van-zuijlen** [comment]
This would still not work with mermaid 10 as it uses CJS loading which was removed, and not ESM loading.

**Comment by brownsarahm** [comment]
@nils-van-zuijlen this patch definitely does work. and it is the **correct** thing to do, mermaid docs [explicitly say to use the jsdeliver cdn](https://mermaid.js.org/config/usage.html#cdn)

see this [requirements.txt](https://github.com/introcompsys/spring2023/blob/main/requirements.txt) that points to the branch this PR is from and an [exmaple rendered diagram](https://introcompsys.github.io/spring2023/notes/2023-02-23.html#git-objects) my [config](https://github.com/introcompsys/spring2023/blob/main/_config.yml#L38-L40) uses all defaults of this package (it is .yml not .py because I am using jupyterbook which wraps sphinx, not sphinx directly)

There are **other** changes that may be necessary, mermaid version 10 does deprecate some things (eg [init](https://mermaid.js.org/config/usage.html#calling-mermaid-init-deprecated) ) that will be removed in verison 11, but this change, to a different CDN host is still independent of other changes.

**Comment by nils-van-zuijlen** [comment]
Yes, this change makes it load v9. And does not allow to load v10 or any further versions.

If you specify `mermaid_version = "10.0.2"` it will not load anything, as v10 does NOT have a mermaid.min.js file. See for yourself: https://cdn.jsdelivr.net/npm/mermaid@10.0.2/dist/mermaid.min.js fails with 404.

In order to be able to load v10, it is required to use ESM loading, as CJS was removed. ESM loading would still work with v9, as it was already available.

**Comment by brownsarahm** [comment]
still what you are pointing out is **additional** changes required, this change should still be included and this is still a better thing to do than to silently convert "latest" to a specific version because it appears to be supported at least for now by mermaid. 

My rendered html currently has included https://cdn.jsdelivr.net/npm/mermaid/dist/mermaid.min.js which works.  Mermaid must still have a 9.x as the default on jsdelivr.

**Comment by mgaitan** [comment]
I'm closing this but totally open for a PR to support the new initialization way based in `ESM` .

**Pull request closed without merging**
